### ISSUE TITLE
Header naviagtions text UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Christopher-Zorc-Store-Dev#1]
Bug - Header navigation buttons text UI issue.
Exp - Header Navigation should be Uppercase and sub options can be capitalised.
Ref link - 
- https://nimb.ws/fiICvu
- https://nimb.ws/Sf2Fiq

**Comment by stores-cedcommerce** [comment]
![image](https://user-images.githubusercontent.com/100198282/166000879-be0ca010-81aa-4ebc-aa89-38b65dd906d2.png)


@ankitcedcoss  sahi kar diya hae

**Comment by ankitcedcoss** [comment]
@stores-cedcommerce Sir, Navigation sub option font size is bigger than navigation heading.
Exp - Sugg - Can we make same font for heading and suboptions.
- https://drive.google.com/file/d/1MwPO8pc00H7mREu0jKra2gOUapraKdc4/view

**Comment by ankitcedcoss** [comment]
Bug Fixed
