### ISSUE TITLE
spacing issue on collection page on responsive - tab and mobile

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Christopher-Zorc-Store-Dev#10]
Bug - Showing spacings above filter button on tab and mobile UI.
Exp - Need to decrease spacings above filter button.
Ref Link - https://drive.google.com/file/d/1Zc-eDeqIucTt0FuvkTLp6kr9IetcLyR-/view

**Comment by stores-cedcommerce** [comment]
this is not an issue @ankitcedcoss

**Comment by ankitcedcoss** [comment]
Bug Fixed
