### ISSUE TITLE
Line spacing issue on footer - desktop and tab

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Christopher-Zorc-Store-Dev#27]
Bug - More spacings added between footer options.
Exp - Sugg - Can user less spacing between option. and line spacing can be same.
Ref Link - https://nimb.ws/Woc97B

**Comment by stores-cedcommerce** [comment]
@ankitcedcoss added space but not required more spacing because in left col has information in paragraph but in other col have links so this is the basic diff.

**Comment by ankitcedcoss** [comment]
Bug Fixed
