### ISSUE TITLE
Page redirection issue on homepage.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Christopher-Zorc-Store-Dev#4]
Bug 1 - User click on 'Read more' button then get redirect on header.
Exp - On about us section user click on read more button then it should get redirect to about us page.
Ref Link - https://drive.google.com/file/d/1EupbSmYa9KZEulu0ypkwZmfDi49uiU6u/view

Bug 2 - Meet our team button not working.
Exp - Button should redirect user to its relevant respective page.
Ref Link - https://drive.google.com/file/d/1BMjDLsqtUGlWUtpoM7s1hB4PViL61k0k/view

**Comment by devAbhishekYadav** [comment]
about us section button redirection now working properly

**Comment by devAbhishekYadav** [comment]
@ankitcedcoss pls retest this issue as it is done

**Comment by ankitcedcoss** [comment]
Bug Fixed
