### ISSUE TITLE
Contact Us page content UI issue on responsive - Mobile

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Christopher-Zorc-Store-Dev#6]
Bug - Contact page content showing misplaced in responsive.
Exp - Contact information contect should show above text field area.
Ref Link - https://drive.google.com/file/d/1W-h3vQl6MQRe4iB_fgxbbv8HEimcrWD2/view

**Comment by stores-cedcommerce** [comment]
Not an issue @ankitcedcoss

**Comment by ankitcedcoss** [comment]
Closed on Not Required
