### ISSUE TITLE
Product page content text UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Internal-Christopher-Zorc-Store-Dev#8]
Bug - Discription text Ui not matched with shipping and about us section text.
Exp - All section text UI should be same on product page.
Ref Link - https://drive.google.com/file/d/1M_62cREvsFsSkBKDgMdnjOk7RmumOSYh/view

**Comment by stores-cedcommerce** [comment]
@ankitcedcoss  this is not in our hand to design, jaesa client update karega vaesa hi aega

**Comment by ankitcedcoss** [comment]
Closed on Not Required
